var interp, __ = [];
  __.unshift({ lineno: 1, filename: __[0].filename });
  __.unshift({ lineno: 1, filename: __[0].filename });
  var friends = (5);
  __.shift();
  __.unshift({ lineno: 4, filename: __[0].filename });
  buf.push('\n<html>');
  __.unshift({ lineno: undefined, filename: __[0].filename });
  __.unshift({ lineno: 5, filename: __[0].filename });
  buf.push('\n  <body>');
  __.unshift({ lineno: undefined, filename: __[0].filename });
  __.shift();
  buf.push('\n  </body>');
  __.shift();
  __.unshift({ lineno: undefined, filename: __[0].filename });
  switch (friends){
  __.unshift({ lineno: 5, filename: __[0].filename });
  __.unshift({ lineno: undefined, filename: __[0].filename });
  case 0:
  __.unshift({ lineno: undefined, filename: __[0].filename });
  __.unshift({ lineno: 6, filename: __[0].filename });
  buf.push('\n  <p>you have no friends');
  __.unshift({ lineno: undefined, filename: __[0].filename });
  __.shift();
  buf.push('\n  </p>');
  __.shift();
  __.shift();
    break;
  __.shift();
  __.unshift({ lineno: undefined, filename: __[0].filename });
  case 1:
  __.unshift({ lineno: undefined, filename: __[0].filename });
  __.unshift({ lineno: 7, filename: __[0].filename });
  buf.push('\n  <p>you have a friend');
  __.unshift({ lineno: undefined, filename: __[0].filename });
  __.shift();
  buf.push('\n  </p>');
  __.shift();
  __.shift();
    break;
  __.shift();
  __.unshift({ lineno: undefined, filename: __[0].filename });
  default:
  __.unshift({ lineno: undefined, filename: __[0].filename });
  __.unshift({ lineno: 8, filename: __[0].filename });
  buf.push('\n  <p>you have ' + escape((interp = friends) == null ? '' : interp) + ' friends');
  __.unshift({ lineno: undefined, filename: __[0].filename });
  __.shift();
  buf.push('\n  </p>');
  __.shift();
  __.shift();
    break;
  __.shift();
  __.shift();
  }
  __.shift();
  __.shift();
  buf.push('\n</html>');
  __.shift();
  __.shift();
